Repository kepler471/moonshot, pull requests merged in 2020-12, with the labels that each got.

#272 (enhancement) Add slowmo effects
  Moonshot/baddies/characters/MotherHen.gd
  Moonshot/baddies/characters/MotherHen.tscn
  Moonshot/main_game.gd
  Moonshot/player/player.gd
  Moonshot/player/player.tscn
Labels: enhancement

#273 New menu framework.
  Moonshot/Menu/Intro.tscn
  Moonshot/Menu/IntroCamera.gd
  Moonshot/Menu/IntroTitles.gd
  Moonshot/Menu/Menu.gd
  Moonshot/Menu/Menu.tscn
  Moonshot/Menu/MenuBase.tscn
  Moonshot/Menu/NerdHerdLogo.tscn
  Moonshot/Menu/Presents.tscn
  Moonshot/Menu/SurfaceBackground.gd
  Moonshot/Menu/assets/IntroBase.png
  Moonshot/Menu/assets/IntroBase.png.import
  Moonshot/Menu/assets/MenuBase.png
  Moonshot/Menu/assets/MenuBase.png.import
  Moonshot/Menu/assets/MenuBaseStructure.png
  Moonshot/Menu/assets/MenuBaseStructure.png.import
  Moonshot/Menu/assets/MySummerInternship.png
  Moonshot/Menu/assets/MySummerInternship.png.import
  Moonshot/Menu/assets/NERDHERDLogo.png
  Moonshot/Menu/assets/NERDHERDLogo.png.import
  Moonshot/Menu/assets/PRESENTS.png
  Moonshot/Menu/assets/PRESENTS.png.import
  Moonshot/Menu/assets/SpaceBackgroundTile.png
  Moonshot/Menu/assets/SpaceBackgroundTile.png.import
  Moonshot/Menu/assets/Spacebackground.png
  Moonshot/Menu/assets/Spacebackground.png.import
  Moonshot/Menu/assets/SurfaceBackground.png
  Moonshot/Menu/assets/SurfaceBackground.png.import
  Moonshot/Menu/assets/Terran.png
  Moonshot/Menu/assets/Terran.png.import
  Moonshot/Menu/fadeinfromblack.gd
  Moonshot/project.godot
  Moonshot/room_templates/next_level_button.gd
Labels: ready for review 🔎

#261 (enhancement, done) Kepler471 more rooms 1
  Moonshot/room_templates/room_scenes/RouteRooms/room_DLR_steli_mid-passage-low-threat.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_DL_steli_mid-length-mid-threat.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_DR_steli_mini-low-threat.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_DR_steli_short-passage.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_LR_steli_v-long-split-dangerpath.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_UDL_steli_midlength-flying-battlezone.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_UDL_steli_short-wasp-threats.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_UDR_steli_small-shortrange-battle.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_UL_steli_wide-dual-route-battle-health.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_UR_steli-medium-platform-safe-health.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_UR_steli_medium-enemy-filled.tscn
  Moonshot/room_templates/unfinished_rooms/room_DLR_steli_mid-passage-low-threat.tscn
  Moonshot/room_templates/unfinished_rooms/room_DLR_steliseed_-5753543975069443628.tscn
  Moonshot/room_templates/unfinished_rooms/room_DLR_steliseed_-9047077326464594679.tscn
  Moonshot/room_templates/unfinished_rooms/room_DL_steli_mid-length-mid-threat.tscn
  Moonshot/room_templates/unfinished_rooms/room_DL_steliseed_-5999109063258218155.tscn
  Moonshot/room_templates/unfinished_rooms/room_DR_steli_mini-low-threat.tscn
  Moonshot/room_templates/unfinished_rooms/room_DR_steli_short-passage.tscn
  Moonshot/room_templates/unfinished_rooms/room_DR_steliseed_808209328609651620.tscn
  Moonshot/room_templates/unfinished_rooms/room_LR_steli_v-long-split-dangerpath.tscn
  Moonshot/room_templates/unfinished_rooms/room_LR_steliseed_4511872451908555718.tscn
  Moonshot/room_templates/unfinished_rooms/room_UDL_steli_midlength-flying-battlezone.tscn
  Moonshot/room_templates/unfinished_rooms/room_UDL_steli_short-wasp-threats.tscn
  Moonshot/room_templates/unfinished_rooms/room_UDR_steli_small-shortrange-battle.tscn
  Moonshot/room_templates/unfinished_rooms/room_UDR_steliseed_-7042056606797869142.tscn
  Moonshot/room_templates/unfinished_rooms/room_UDR_steliseed_1417398501829199279.tscn
  Moonshot/room_templates/unfinished_rooms/room_UDR_steliseed_6569097726357701193.tscn
  Moonshot/room_templates/unfinished_rooms/room_UL_steli_wide-dual-route-battle-health.tscn
  Moonshot/room_templates/unfinished_rooms/room_UL_steliseed_3658496039839094366.tscn
  Moonshot/room_templates/unfinished_rooms/room_UR_steli-medium-platform-safe-health.tscn
  Moonshot/room_templates/unfinished_rooms/room_UR_steli_medium-enemy-filled.tscn
  Moonshot/room_templates/unfinished_rooms/room_UR_steliseed_-4675197905101474380.tscn
  Moonshot/room_templates/unfinished_rooms/room_UR_steliseed_-5781492163454328648.tscn
Labels: enhancement, ready for review 🔎

#281 Menu Buttons Enhancement
  Moonshot/Menu/ExitButton.gd
  Moonshot/Menu/Menu.gd
  Moonshot/Menu/Menu.tscn
  Moonshot/Menu/PlayButton.gd
  Moonshot/Menu/assets/EXIT.png
  Moonshot/Menu/assets/EXIT.png.import
  Moonshot/Menu/assets/PLAY.png
  Moonshot/Menu/assets/PLAY.png.import
Labels: ready for review 🔎
