Repository kepler471/moonshot, pull requests merged in 2020-11, with the labels that each got.

#69 Player tweak mechanics
  Moonshot/Combat/bullet.gd
  Moonshot/StateMachine/StateMachine.gd
  Moonshot/player/States/air.gd
  Moonshot/player/States/move.gd
  Moonshot/player/States/wall.gd
  Moonshot/player/player.gd
  Moonshot/player/player.tscn
  Moonshot/project.godot
Labels: bug, enhancement

#75 (fixes) Bear boi RayCast to detect areas and bodies
  Moonshot/baddies/BearBoi.tscn
Labels: bug

#78 Allow wall dropoff
  Moonshot/player/LedgeWallDetector.gd
  Moonshot/player/LedgeWallDetector.tscn
  Moonshot/player/States/air.gd
  Moonshot/player/States/ledge.gd
  Moonshot/player/States/move.gd
  Moonshot/player/States/wall.gd
  Moonshot/player/player.tscn
Labels: in review

#86 Player variable jumps and air resistance
  Moonshot/player/States/air.gd
Labels: enhancement

#67 room_CANVAS for new rooms
  Moonshot/room_CANVAS.tscn
Labels: 🎉 approved 🎉

#89 Make player face mouse in every state
  Moonshot/player/player.gd
Labels: enhancement

#88 Increase player and arm Z index
  Moonshot/player/player.tscn
Labels: bug, 🎉 approved 🎉

#81 (enhancement): ceiling bear boi & baddie lasers
  Moonshot/Autoload/CombatSignalController.gd
  Moonshot/baddies/BaddieLaser/BaddieBullet.gd
  Moonshot/baddies/BaddieLaser/BaddieBullet.tscn
  Moonshot/baddies/BaddieLaser/BaddieLaserPointer.gd
  Moonshot/baddies/BaddieLaser/BaddieLaserPointer.tscn
  Moonshot/baddies/BearCeilingBoi.gd
  Moonshot/baddies/BearCeilingBoi.tscn
  Moonshot/player/player.gd
  Moonshot/project.godot
Labels: in review

#94 new baddy: Droppy Boi, added to SplashScreen.tscn
  Moonshot/SplashScreen.tscn
  Moonshot/baddies/BearDroppyBoi.gd
  Moonshot/baddies/BearDroppyBoi.tscn
  Moonshot/project.godot
Labels: enhancement

#92 Added one-way platforms
  Moonshot/assets/tile_maps/DeepPurpleTiles.png
  Moonshot/assets/tile_maps/DeepTealTiles.png
  Moonshot/assets/tile_maps/TileSet_v1.tres
  Moonshot/player/assets/32x32_Medic/MEDICrunstart.png.import
  Moonshot/player/assets/MEDILatch.png.import
  Moonshot/room_CANVAS.tscn
Labels: 🎉 approved 🎉

#96 chore: shooty boi sprites
  Moonshot/baddies/sprites/ShootyBoi/shooter0.png
  Moonshot/baddies/sprites/ShootyBoi/shooter0.png.import
  Moonshot/baddies/sprites/ShootyBoi/shooter1.png
  Moonshot/baddies/sprites/ShootyBoi/shooter1.png.import
  Moonshot/baddies/sprites/ShootyBoi/shooter2.png
  Moonshot/baddies/sprites/ShootyBoi/shooter2.png.import
  Moonshot/baddies/sprites/ShootyBoi/shooter3.png
  Moonshot/baddies/sprites/ShootyBoi/shooter3.png.import
  Moonshot/baddies/sprites/ShootyBoi/shooter4.png
  Moonshot/baddies/sprites/ShootyBoi/shooter4.png.import
Labels: 🎉 approved 🎉

#93 Grace counter for wall jump.
  Moonshot/player/States/wall.gd
Labels: in review

#101 chore: Idle animation cleanup
  Moonshot/player/assets/idle/Medic1TALL0.png
  Moonshot/player/assets/idle/Medic1TALL1.png
  Moonshot/player/assets/idle/Medic1TALL2.png
  Moonshot/player/assets/run/MEDICrun0.png
  Moonshot/player/assets/run/MEDICrun1.png
  Moonshot/player/assets/run/MEDICrun2.png
  Moonshot/player/assets/run/MEDICrun3.png
  Moonshot/player/assets/run/MEDICrun4.png
  Moonshot/player/assets/run/MEDICrun5.png
  Moonshot/player/assets/run/MEDICrun6.png
  Moonshot/player/assets/run/MEDICrun7.png
  Moonshot/player/assets/run/MEDICrun8.png
  Moonshot/player/assets/run/MEDICrun9.png
  Moonshot/player/player.tscn
  Moonshot/project.godot
Labels: chore, 🎉 approved 🎉

#121 (fix #87): baddie checking for colliding body
  Moonshot/baddies/Baddie.gd
Labels: 🎉 approved 🎉

#99 enhancement: spawn location
  Moonshot/procedural_map_generation/Room.gd
  Moonshot/procedural_map_generation/floor_generator.gd
  Moonshot/room_templates/BaseRoom2.tscn
  Moonshot/room_templates/entrance_to_room.tscn
  Moonshot/room_templates/room_3_junction_LEFT.tscn
  Moonshot/room_templates/room_scenes/room_3_junction_DOWN.tscn
  Moonshot/room_templates/room_scenes/room_3_junction_LEFT.tscn
  Moonshot/room_templates/room_scenes/room_3_junction_RIGHT.tscn
  Moonshot/room_templates/room_scenes/room_3_junction_UP.tscn
  Moonshot/room_templates/room_scenes/room_base.tscn
  Moonshot/room_templates/room_scenes/room_corner_DOWN_LEFT.tscn
  Moonshot/room_templates/room_scenes/room_corner_DOWN_RIGHT.tscn
  Moonshot/room_templates/room_scenes/room_corner_UP_LEFT.tscn
  Moonshot/room_templates/room_scenes/room_corner_UP_RIGHT.tscn
  Moonshot/room_templates/room_scenes/room_corridor_LEFT_RIGHT.tscn
  Moonshot/room_templates/room_scenes/room_corridor_UP_DOWN.tscn
  Moonshot/room_templates/room_scenes/room_test_down_entrance.tscn
  Moonshot/room_templates/room_scenes/room_test_left_entrance.tscn
  Moonshot/room_templates/room_scenes/room_test_right_entrance.tscn
  Moonshot/room_templates/room_scenes/room_test_up_entrance.tscn
  Moonshot/room_templates/room_test_down_entrance.tscn
  Moonshot/room_templates/room_test_left_entrance.tscn
  Moonshot/room_templates/room_test_right_entrance.tscn
  Moonshot/room_templates/room_test_up_entrance.tscn
Labels: enhancement, in review

#123 Health item
  Moonshot/SplashScreen.tscn
  Moonshot/items_objects/assets/HealthPickup.png
  Moonshot/items_objects/assets/HealthPickup.png.import
  Moonshot/items_objects/health_pickup.gd
  Moonshot/items_objects/health_pickup.tscn
  Moonshot/main_game.tscn
  Moonshot/player/player.gd
  Moonshot/room_templates/room_scenes/room_base.tscn
Labels: Blocked

#125 Updated room_CANVAS.tscn room template that can be copied across for new room templates
  Moonshot/SplashScreen.tscn
  Moonshot/items_objects/breakable_tile_purple.tscn
  Moonshot/items_objects/breakable_tile_teal.tscn
  Moonshot/items_objects/health_pickup.tscn
  Moonshot/room_CANVAS.tscn
  Moonshot/room_templates/room_scenes/room_base.tscn
Labels: chore, 🎉 approved 🎉

#126 fix: baddies spin rapidly when on edge of ledge
  Moonshot/baddies/BearBoi.gd
  Moonshot/baddies/BearBoi.tscn
  Moonshot/baddies/BearCeilingBoi.gd
  Moonshot/baddies/BearCeilingBoi.tscn
  Moonshot/baddies/BearDroppyBoi.gd
  Moonshot/baddies/BearDroppyBoi.tscn
  Moonshot/baddies/TurningHack.gd
  Moonshot/baddies/TurningHack.tscn
Labels: in review

#130 (fix #97): player sprite animation name
  Moonshot/player/player.gd
Labels: in review

#132 (chore #131): breakable objects 3 shots
  Moonshot/items_objects/breakable_tile.gd
Labels: in review

#133 (enhancement) cursor given fixed position from player
  Moonshot/player/player.gd
  Moonshot/player/player.tscn
Labels: enhancement

#139 (enhancement): Add stagger
  Moonshot/Autoload/CombatSignalController.gd
  Moonshot/baddies/Baddie.gd
  Moonshot/baddies/BaddieLaser/BaddieBullet.gd
  Moonshot/player/States/air.gd
  Moonshot/player/States/stagger.gd
  Moonshot/player/assets/stagger/MediSTAGGER.png
  Moonshot/player/assets/stagger/MediSTAGGER.png.import
  Moonshot/player/player.gd
  Moonshot/player/player.tscn
Labels: enhancement

#129 (enhancement #107): baddies fadeout
  Moonshot/Animations/Fade.gd
  Moonshot/SplashScreen.tscn
  Moonshot/baddies/Baddie.gd
  Moonshot/baddies/BearBoi.gd
  Moonshot/baddies/BearBoi.tscn
  Moonshot/baddies/BearCeilingBoi.gd
  Moonshot/baddies/BearCeilingBoi.tscn
  Moonshot/baddies/BearDroppyBoi.gd
  Moonshot/baddies/BearDroppyBoi.tscn
  Moonshot/baddies/FlyBoi.gd
  Moonshot/baddies/FlyBoi.tscn
  Moonshot/project.godot
Labels: in review

#141 Stats module
  Moonshot/Autoload/Utils.gd
  Moonshot/main_game.gd
  Moonshot/player/player.gd
  Moonshot/splash_screen.gd
Labels: 🎉 approved 🎉

#142 (enhancement: #74): Wall shooty boi
  Moonshot/Autoload/Utils.gd
  Moonshot/SplashScreen.tscn
  Moonshot/baddies/Baddie.gd
  Moonshot/baddies/BaddieLaser/BaddieBullet.gd
  Moonshot/baddies/FlyBoi.tscn
  Moonshot/baddies/WallBoi.gd
  Moonshot/baddies/WallBoi.tscn
  Moonshot/player/player.gd
Labels: in review

#149 (fix) mouse capture only when asked for
  Moonshot/player/player.gd
  Moonshot/project.godot
Labels: bug, enhancement

#151 chore: baddie refactor
  Moonshot/Autoload/BaddieSpawner.gd
  Moonshot/Autoload/Utils.gd
  Moonshot/Combat/bullet.tscn
  Moonshot/SplashScreen.tscn
  Moonshot/baddies/Attributes.gd
  Moonshot/baddies/Baddie.gd
  Moonshot/baddies/BaddieInterface.gd
  Moonshot/baddies/BearBoi.gd
  Moonshot/baddies/BearCeilingBoi.gd
  Moonshot/baddies/FlyBoi.gd
  Moonshot/baddies/WallBoi.gd
  Moonshot/baddies/characters/BearBoi.gd
  Moonshot/baddies/characters/BearBoi.tscn
  Moonshot/baddies/characters/BearCeilingBoi.gd
  Moonshot/baddies/characters/BearCeilingBoi.tscn
  Moonshot/baddies/characters/BearDroppyBoi.gd
  Moonshot/baddies/characters/BearDroppyBoi.tscn
  Moonshot/baddies/characters/FlyBoi.gd
  Moonshot/baddies/characters/FlyBoi.tscn
  Moonshot/baddies/characters/WallBoi.gd
  Moonshot/baddies/characters/WallBoi.tscn
  Moonshot/procedural_map_generation/Room.gd
  Moonshot/project.godot
  Moonshot/room_CANVAS.tscn
  Moonshot/room_templates/room_scenes/room_base.tscn
Labels: chore, in review

#155 chore: builder for setting attributes upstream
  Moonshot/Autoload/BaddieSpawner.gd
  Moonshot/baddies/Attributes.gd
  Moonshot/baddies/characters/BearBoi.gd
  Moonshot/baddies/characters/BearBoi.tscn
  Moonshot/baddies/characters/BearCeilingBoi.gd
  Moonshot/baddies/characters/BearCeilingBoi.tscn
  Moonshot/baddies/characters/BearDroppyBoi.gd
  Moonshot/baddies/characters/BearDroppyBoi.tscn
  Moonshot/baddies/characters/FlyBoi.gd
  Moonshot/baddies/characters/FlyBoi.tscn
  Moonshot/baddies/characters/WallBoi.gd
  Moonshot/baddies/characters/WallBoi.tscn
  Moonshot/procedural_map_generation/BaddieBuilder.gd
  Moonshot/procedural_map_generation/Room.gd
  Moonshot/project.godot
Labels: chore

#159 fix: fade
  Moonshot/Animations/Fade.gd
  Moonshot/baddies/Attributes.gd
Labels: bug

#160 Difficulty controller now in charge of level difficulty
  Moonshot/procedural_map_generation/DifficultyController.gd
  Moonshot/procedural_map_generation/Room.gd
Labels: chore, enhancement, in review, 🎉 approved 🎉

#164 Fix: Ray-detection-update
  Moonshot/player/LedgeWallDetector.gd
  Moonshot/player/States/wall.gd
Labels: in review

#158 Enhancement: DAMAGE TILES
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool.tres
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool1.png
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool1.png.import
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool2.png
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool2.png.import
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool3.png
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool3.png.import
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool4.png
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool4.png.import
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool5.png
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool5.png.import
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool6.png
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool6.png.import
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool7.png
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool7.png.import
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool8.png
  Moonshot/assets/tile_maps/InfectionPool/InfectionPool8.png.import
  Moonshot/assets/tile_maps/TileSet_v1.tres
  Moonshot/player/States/stagger.gd
  Moonshot/player/player.gd
  Moonshot/project.godot
  Moonshot/room_CANVAS.tscn
Labels: enhancement, in review, 🎉 approved 🎉

#173 (enhancement #106): flashing baddie
  Moonshot/Animations/Fade.gd
  Moonshot/baddies/Attributes.gd
Labels: in review

#175 chore: recalibrate baddies
  Moonshot/baddies/characters/BearCeilingBoi.gd
  Moonshot/baddies/characters/BearDroppyBoi.gd
  Moonshot/baddies/characters/FlyBoi.gd
Labels: chore, in review

#184 enhancement: tanky boi
  Moonshot/baddies/characters/TankyBoi.gd
  Moonshot/baddies/characters/TankyBoi.tscn
  Moonshot/procedural_map_generation/DifficultyController.gd
  Moonshot/project.godot
Labels: enhancement

#186 fix: tanky boi hot fix
  Moonshot/baddies/characters/TankyBoi.gd
Labels: 🎉 approved 🎉

#181 Enhancement: Tile System BETA
  Moonshot/Autoload/TileSheetLoader.gd
  Moonshot/SplashScreen.tscn
  Moonshot/assets/tile_maps/Damage_TileSet.tres
  Moonshot/assets/tile_maps/Infection Wall/InfectionWall.png
  Moonshot/assets/tile_maps/Infection Wall/InfectionWall.png.import
  Moonshot/assets/tile_maps/TileMap.gd
  Moonshot/assets/tile_maps/TileSet_v1.tres
  Moonshot/assets/tile_maps/base_tiles/Blue1.png
  Moonshot/assets/tile_maps/base_tiles/Blue1.png.import
  Moonshot/assets/tile_maps/base_tiles/Blue2.png
  Moonshot/assets/tile_maps/base_tiles/Blue2.png.import
  Moonshot/assets/tile_maps/base_tiles/Green1.png
  Moonshot/assets/tile_maps/base_tiles/Green1.png.import
  Moonshot/assets/tile_maps/base_tiles/Green2.png
  Moonshot/assets/tile_maps/base_tiles/Green2.png.import
  Moonshot/assets/tile_maps/base_tiles/Grey.png
  Moonshot/assets/tile_maps/base_tiles/Grey.png.import
  Moonshot/assets/tile_maps/base_tiles/Ice.png
  Moonshot/assets/tile_maps/base_tiles/Ice.png.import
  Moonshot/assets/tile_maps/base_tiles/Pink.png
  Moonshot/assets/tile_maps/base_tiles/Pink.png.import
  Moonshot/assets/tile_maps/base_tiles/Purple.png
  Moonshot/assets/tile_maps/base_tiles/Purple.png.import
  Moonshot/assets/tile_maps/base_tiles/Red1.png
  Moonshot/assets/tile_maps/base_tiles/Red1.png.import
  Moonshot/assets/tile_maps/base_tiles/Red2.png
  Moonshot/assets/tile_maps/base_tiles/Red2.png.import
  Moonshot/assets/tile_maps/base_tiles/Teal1.png
  Moonshot/assets/tile_maps/base_tiles/Teal1.png.import
  Moonshot/assets/tile_maps/base_tiles/Teal2.png
  Moonshot/assets/tile_maps/base_tiles/Teal2.png.import
  Moonshot/assets/tile_maps/base_tiles/Yellow1.png
  Moonshot/assets/tile_maps/base_tiles/Yellow1.png.import
  Moonshot/assets/tile_maps/base_tiles/Yellow2.png
  Moonshot/assets/tile_maps/base_tiles/Yellow2.png.import
  Moonshot/main_game.gd
  Moonshot/player/LedgeWallDetector.gd
  Moonshot/player/player.gd
  Moonshot/project.godot
  Moonshot/room_CANVAS.tscn
Labels: in review

#187 (fix #157 and other new bugs) Fix death and stagger bugs
  Moonshot/player/States/die.gd
  Moonshot/player/player.gd
Labels: bug

#189 (enhancement): mother hen
  Moonshot/baddies/BaddieLaser/BaddieSpawner.gd
  Moonshot/baddies/BaddieLaser/BaddieSpawner.tscn
  Moonshot/baddies/characters/MotherHen.gd
  Moonshot/baddies/characters/MotherHen.tscn
  Moonshot/project.godot
Labels: enhancement, ready for review 🔎

#198 (enhancement) tweaking gravity for nicer player feel
  Moonshot/player/States/move.gd
  Moonshot/player/States/run.gd
  Moonshot/player/States/wall.gd
  Moonshot/player/player.tscn
Labels: enhancement

#197 (enhancement) replace rectangle with capsule shape
  Moonshot/player/player.tscn
Labels: enhancement

#195 (patch) Improved sprite alignment
  Moonshot/player/player.tscn
Labels: enhancement

#182 Weapons created, no items yet
  Moonshot/Autoload/Utils.gd
  Moonshot/Combat/bullet.gd
  Moonshot/SplashScreen.tscn
  Moonshot/items_objects/assets/WeaponIcons/LaserBlasterIcon.png
  Moonshot/items_objects/assets/WeaponIcons/LaserBlasterIcon.png.import
  Moonshot/items_objects/assets/WeaponIcons/MachineGunIcon.png
  Moonshot/items_objects/assets/WeaponIcons/MachineGunIcon.png.import
  Moonshot/items_objects/assets/WeaponIcons/ShotgunIcon.png
  Moonshot/items_objects/assets/WeaponIcons/ShotgunIcon.png.import
  Moonshot/items_objects/assets/WeaponIcons/TwinBlasterIcon.png
  Moonshot/items_objects/assets/WeaponIcons/TwinBlasterIcon.png.import
  Moonshot/items_objects/weapon_pickups/LaserBlaster.gd
  Moonshot/items_objects/weapon_pickups/LaserBlaster.tscn
  Moonshot/items_objects/weapon_pickups/MachineGun.gd
  Moonshot/items_objects/weapon_pickups/MachineGun.tscn
  Moonshot/items_objects/weapon_pickups/Shotgun.gd
  Moonshot/items_objects/weapon_pickups/Shotgun.tscn
  Moonshot/items_objects/weapon_pickups/TwinShot.gd
  Moonshot/items_objects/weapon_pickups/TwinShot.tscn
  Moonshot/main_game.gd
  Moonshot/main_game.tscn
  Moonshot/player/PlayerArsenal.gd
  Moonshot/player/player.gd
  Moonshot/player/player.tscn
  Moonshot/room_templates/room_scenes/room_base.tscn
Labels: enhancement

#208 (enhancement) new bullet sprite, added collision animation
  Moonshot/Combat/bullet.gd
  Moonshot/Combat/bullet.tscn
  Moonshot/assets/projectiles/bullhit-Sheet.png
  Moonshot/assets/projectiles/bullhit-Sheet.png.import
  Moonshot/assets/projectiles/specbulle-sheet.png
  Moonshot/assets/projectiles/specbulle-sheet.png.import
Labels: enhancement

#207 Fixed firerate not dropping on damage bug
  Moonshot/Combat/Stats.gd
  Moonshot/player/player.gd
Labels: bug

#216 (fix) Ghosty self collision and buff
  Moonshot/baddies/BaddieLaser/Blob.tscn
  Moonshot/baddies/characters/GhostyBoi.gd
  Moonshot/baddies/characters/GhostyBoi.tscn
Labels: bug, enhancement

#221 fix: baddies colliding with each other
  Moonshot/baddies/characters/BearBoi.tscn
  Moonshot/baddies/characters/BearCeilingBoi.tscn
  Moonshot/baddies/characters/BearDroppyBoi.tscn
Labels: ready for review 🔎

#209 Have moved HUD code into a seperate script
  Moonshot/HUD.gd
  Moonshot/main_game.gd
Labels: chore

#212 Enhancement: Player SFX
  Moonshot/default_bus_layout.tres
  Moonshot/player/PlayerArsenal.gd
  Moonshot/player/PlayerAudio.gd
  Moonshot/player/States/move.gd
  Moonshot/player/States/run.gd
  Moonshot/player/States/wall.gd
  Moonshot/player/assets/sounds/blaster_v1.wav
  Moonshot/player/assets/sounds/blaster_v1.wav.import
  Moonshot/player/assets/sounds/deathgrunt.wav
  Moonshot/player/assets/sounds/deathgrunt.wav.import
  Moonshot/player/assets/sounds/game-pick-up-object.wav
  Moonshot/player/assets/sounds/game-pick-up-object.wav.import
  Moonshot/player/assets/sounds/healthpickup.wav
  Moonshot/player/assets/sounds/healthpickup.wav.import
  Moonshot/player/assets/sounds/jump.wav
  Moonshot/player/assets/sounds/jump.wav.import
  Moonshot/player/assets/sounds/paingrunt.wav
  Moonshot/player/assets/sounds/paingrunt.wav.import
  Moonshot/player/assets/sounds/running.wav
  Moonshot/player/assets/sounds/running.wav.import
  Moonshot/player/assets/sounds/sizzle.wav
  Moonshot/player/assets/sounds/sizzle.wav.import
  Moonshot/player/assets/sounds/wallsliding.wav
  Moonshot/player/assets/sounds/wallsliding.wav.import
  Moonshot/player/player.gd
  Moonshot/player/player.tscn
Labels: enhancement, in review

#218 (fix) get direction input to find dodge direction
  Moonshot/player/States/dodge.gd
  Moonshot/player/player.gd
Labels: bug, enhancement, ready for review 🔎

#220 (fix #79) Single step drop fix
  Moonshot/player/FloorDetector.tscn
  Moonshot/player/States/run.gd
Labels: bug, ready for review 🔎

#222 Minimap boundaries
  Moonshot/HUD.gd
  Moonshot/main_game.gd
  Moonshot/main_game.tscn
  Moonshot/procedural_map_generation/draw_map.gd
Labels: chore

#232 fixes: firerate performance, empty array for baddies and animation on node
  Moonshot/Combat/bullet.gd
  Moonshot/baddies/BaddieLaser/Blob.gd
  Moonshot/items_objects/item_pickups/FirerateDropUnlock.gd
  Moonshot/items_objects/item_pickups/FireratePickup.gd
  Moonshot/room_templates/BaseRoom.gd
Labels: bug, ready for review 🔎

#234 (enhancement) Spawn safely
  Moonshot/main_game.gd
  Moonshot/player/States/spawn.gd
  Moonshot/player/assets/shield.png
  Moonshot/player/assets/shield.png.import
  Moonshot/player/player.gd
  Moonshot/player/player.tscn
  Moonshot/splash_screen.gd
Labels: bug, enhancement, ready for review 🔎

#252 (fix) game breaks without these...
  Moonshot/room_templates/room_scenes/BossRooms/room_test_down_entrance.tscn
  Moonshot/room_templates/room_scenes/BossRooms/room_test_left_entrance.tscn
  Moonshot/room_templates/room_scenes/BossRooms/room_test_right_entrance.tscn
  Moonshot/room_templates/room_scenes/BossRooms/room_test_up_entrance.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_3_junction_DOWN.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_3_junction_LEFT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_3_junction_RIGHT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_3_junction_UP.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corner_DOWN_LEFT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corner_DOWN_RIGHT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corner_UP_LEFT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corner_UP_RIGHT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corridor_LEFT_RIGHT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corridor_UP_DOWN.tscn
Labels: bug

#253 fix: fade out yeilding after leaving tree
  Moonshot/Animations/Fade.gd
  Moonshot/baddies/Attributes.gd
  Moonshot/baddies/characters/BearDroppyBoi.gd
Labels: bug, ready for review 🔎

#254 add delay timer
  Moonshot/main_game.gd
Labels: bug

#257 fix: remove baddie when dead, not fade out
  Moonshot/baddies/Attributes.gd
  Moonshot/baddies/characters/TankyBoi.gd
Labels: bug, ready for review 🔎

#258 enhancement: James rooms
  Moonshot/room_templates/room_scenes/RouteRooms/room_D_james11.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_LR_james45.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_ULR_james12.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/route_DL_james14.tscn
Labels: ready for review 🔎

#264 Fix: Big Debug Error cleanup.
  Moonshot/Combat/Stats.gd
  Moonshot/HUD.gd
  Moonshot/baddies/Attributes.gd
  Moonshot/baddies/characters/BearBoi.gd
  Moonshot/baddies/characters/BearCeilingBoi.gd
  Moonshot/baddies/characters/BearDroppyBoi.gd
  Moonshot/baddies/characters/FlyBoi.gd
  Moonshot/baddies/characters/GhostyBoi.gd
  Moonshot/baddies/characters/MotherHen.gd
  Moonshot/baddies/characters/TankyBoi.gd
  Moonshot/baddies/characters/WallBoi.gd
  Moonshot/main_game.gd
  Moonshot/player/LedgeWallDetector.gd
  Moonshot/player/PlayerArsenal.gd
  Moonshot/player/PlayerAudio.gd
  Moonshot/player/States/ledge.gd
  Moonshot/procedural_map_generation/DifficultyController.gd
  Moonshot/procedural_map_generation/draw_map.gd
  Moonshot/procedural_map_generation/level_gen.gd
  Moonshot/project.godot
  Moonshot/room_templates/BaseRoom.gd
  Moonshot/room_templates/next_level_button.gd
  Moonshot/splash_screen.gd
Labels: bug, ready for review 🔎

#260 Fix: Healthpickup error
  Moonshot/items_objects/item_pickups/HealthPickup.tscn
Labels: bug, ready for review 🔎

#259 Fix: Minimap gui box filepath patch.
  Moonshot/main_game.gd
Labels: bug, ready for review 🔎

#265 Chore: Old room removal.
  Moonshot/room_templates/room_scenes/BossRooms/room_U_billyBoss_temp.tscn
  Moonshot/room_templates/room_scenes/BossRooms/room_test_down_entrance.tscn
  Moonshot/room_templates/room_scenes/BossRooms/room_test_left_entrance.tscn
  Moonshot/room_templates/room_scenes/BossRooms/room_test_right_entrance.tscn
  Moonshot/room_templates/room_scenes/BossRooms/room_test_up_entrance.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_3_junction_DOWN.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_3_junction_LEFT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_3_junction_RIGHT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_3_junction_UP.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_DR_billy1.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_D_james9.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_UR_james10.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corner_DOWN_LEFT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corner_DOWN_RIGHT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corner_UP_LEFT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corner_UP_RIGHT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corridor_LEFT_RIGHT.tscn
  Moonshot/room_templates/room_scenes/RouteRooms/room_corridor_UP_DOWN.tscn
Labels: chore, ready for review 🔎

#267 (enhancement #202) Baddies new flying type
  Moonshot/baddies/characters/Waspy.gd
  Moonshot/baddies/characters/Waspy.tscn
  Moonshot/baddies/sprites/Flightywhip-Sheet.png
  Moonshot/baddies/sprites/Flightywhip-Sheet.png.import
Labels: enhancement, ready for review 🔎

#270 (enhancement) mother death animation and elevator activation
  Moonshot/baddies/characters/MotherHen.gd
  Moonshot/baddies/characters/MotherHen.tscn
  Moonshot/baddies/sprites/panel1.png
  Moonshot/baddies/sprites/panel1.png.import
  Moonshot/baddies/sprites/panel2.png
  Moonshot/baddies/sprites/panel2.png.import
Labels: enhancement, ready for review 🔎
